export const jobs = [
    {
        "employer_name": "Creator.co",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR06UryQXI00W1T2ogk6xL4bfMVqgU-tuF9WOwq&s=0",
        "employer_website": null,
        "job_id": "nO7vSCRJZzcAAAAAAAAAAA==",
        "job_title": "Intermediate/Senior Web Developer",
        "job_apply_link": "https://ca.linkedin.com/jobs/view/intermediate-senior-web-developer-at-creator-co-3564042610",
        "job_description": "About the job\n\nWe are Creator.co! A top-ranked Influencer Marketing platform growing in Vancouver, BC.\n\nAs our community blossoms to the north of 150,000 members, we're building features and programs to help our community of micro-influencers connect with more brands, collaborate, grow, and earn more money.\n\nIn this role, duties will include the following:\n\nDeveloping information systems by studying operations; designing, developing and installing software solutions; supporting and developing software teams. The Intermediate/Senior Web Developer will help lead a team of developers responsible for building new and supporting existing features/products.\n\nAbility to prioritize well, communicate clearly, have a consistent track record of delivery and excellent software engineering skills.\n\nCreative engineering, balanced with high quality and a customer focus, must be able to work across multiple facets of the project and juggle multiple responsibilities simultaneously, with strong analytic capability and the ability to create innovative solutions.\n\nWe are looking for a highly motivated individual looking to grow their career in a fast-paced environment.\n\nResponsibilities:\n• Develop software solutions by studying information needs; conferring with users; studying systems flow, data usage and work processes; investigating problem areas; following the software development lifecycle.\n• Determine operational feasibility by evaluating analysis, problem definition, requirements, solution development and proposed solutions.\n• Document and demonstrate solutions by developing documentation, flowcharts, layouts, diagrams, charts, code comments and clear code\n• Prepare and install solutions by determining and designing system specifications, standards and programming.\n• Improve operations by conducting systems analysis; recommending changes in policies and procedures.\n• Update job knowledge by studying state-of-the-art development tools, programming techniques and computing equipment; participating in educational opportunities; reading professional publications; maintaining personal networks; participating in professional organizations.\n• Protect operations by keeping information confidential.\n• Provide information by collecting, analyzing and summarizing development and service issues.\n• Accomplish engineering and organization mission by completing related results as needed.\n• Support and develop software engineers by providing advice, coaching and educational opportunities.\n• First and foremost, developing software our users need\n• Mentor junior and mid-level engineers\n• Collaborate with the team to brainstorm and create new products\n• Grow engineering teams by interviewing, recruiting and hiring\n• Make informed decisions quickly and take ownership of services and applications at scale\n• Work collaboratively with others to achieve goals\n• Be a persistent, creative problem solver\n• Remain calm and effective in a crisis\n• Stay on the leading edge of development practices\n• Passionate about great technologies, especially open source\n• Understand business needs and know how to create the tools to manage them\n\nPlease include your GitHub account in your resume.\n\nQualifications:\n• 2-5 years of experience working with nodejs frameworks, backend/DevOps and full-stack web development.\n• Fluent and experienced in nodejs/expressjs/react/sql databases & experience with different aspects of DevOps (eg. CI/CD, performance monitoring, security, etc.) would be handy\n• Either strong OOP or Functional Programing and modelling skills\n• Experience working in an agile environment\n• Experience building complex web systems that have been successfully delivered to customers\n• Ability to take a project from scoping requirements through the actual launch of the project\n• Experience in communicating with users, other technical teams and management to collect requirements, identify tasks, provide estimates and meet production deadlines\n• Experience with mission-critical, 24x7 systems\n• Experience implementing and consuming large-scale web services\n• Experience developing software utilizing workflow\n• Experience with professional software engineering best practices for the entire software development life cycle, including coding standards, code reviews, source control management, build processes, testing and operations\n• Eagerness and willingness to learn new technologies",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": 24,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-05-14T22:18:02.000Z",
        "job_posted_at_datetime_utc": "2023-04-14T22:18:02.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "Create Music Group",
        "employer_logo": "http://performermag.com/wp-content/uploads/2019/08/create-music-group-2019-billboard-1548.jpg",
        "employer_website": "https://createmusicgroup.com",
        "job_id": "Sf5tOuLsGowAAAAAAAAAAA==",
        "job_title": "Senior Front End Developer",
        "job_apply_link": "https://www.ziprecruiter.com/c/Create-Music-Group/Job/Senior-Front-End-Developer/-in-Vancouver,BC?jid=945e708c13310fc1",
        "job_description": "Create Music Group is an LA-based digital music company that provides artists and labels with distribution, rights management, and creative services. We monetize over 12 billion monthly music streams and have collected over $150 Million in previously unclaimed revenue for artists and labels. Clients include Future,Playboi Carti, JLo, City Girls, Marshmello, Don Diablo, Trippie Redd, Migos, and more.\n\nFlighthouse, a division of Create Music Group, is the largest music tastemaker on TikTok with 23M followers & growing. We work directly with the internet’s most popular influencers, labels, artists and brands to develop and execute unique entertainment content and campaigns catered to Generation Z.\n\nWe were named Inc.'s #2 fastest growing company in 2020. We welcome you to join us in our effort to help artists be in control!\n\nSUMMARY:\n\nWe’re looking for a Senior Frontend Developer who is passionate about unique designs in well-crafted web applications as we rapidly scale our products and organization. Create is looking for talented engineers who love to tackle daily challenges while making a big impact in a collaborative and engaging environment. Our goal is to support each other’s growth and development while building tools that advance the music industry to modernize the way artists create, distribute, and get paid.\n\nRESPONSIBILITIES:\n• Implement UX/UI workflows and designs\n• Plan and write code for features in accordance to business requirements\n• Refine requirements, use cases, and workflows with the Designer(s)\n• Communicate, collaborate, and troubleshoot on development tasks\n• Support the development and maintenance of the development environmentWrite tests for integration testing\n• Write documentation and review code with peers\n\nQUALIFICATIONS\n• Bachelor's degree in Computer Science, Engineering or related field, or equivalent training, fellowship, or work experience\n• 4+ years of front-end development building web applications and thoroughly understanding HTML, CSS, JS, and their interactions\n• Extremely well versed in React and latest features\n• Experience with writing unit tests and working with frameworks such as Mocha, Jest & Jasmine\n• Experience with converting design files into responsive HTML, CSS, and JS\n• Familiarity with JavaScript bundlers (Webpack)\n• Proficiency with version control (Git) and building scalable applications\n• Experience in developing responsive cross-browser/cross-platform UIs for web applications\n• Have an understanding of the agile methodologies\n• Proficiency with ES6 and it’s best practices preferred\n• Proficiency with Postman, Pivotal Tracker / Jira preferre\n• Experience with Programming Languages (PHP, Python, etc.) preferred\n\nBENEFITS:\n• 15 days paid vacation, 5 paid personal days, and 6 paid sick days per year\n• 12 paid company holidays per year for Canadians\n• Top-tier extended health, vision, and dental insurance coverage for you and your dependents\n• Health Spending Account (myHSA) for you and your dependents\n• Employee Assistance Program (access to counseling for mental health, legal and financial counseling, career coaching, etc.)\n• Life insurance, AD&D, Short and Long Term Disability Benefits\n• Internal opportunities for professional development and advancement\n• Free access to online educational resources\n• Opportunity to travel to our Hollywood HQ in California\n\nCOVID-19 CONSIDERATIONS\n• Our Data and Engineering Teams are currently working fully remote. Team members in Vancouver, BC meet once a month to work together at a flex space downtown. All interviews and subsequent meetings will be conducted online using Google Meet.\n\nPAY SCALE\n• Base salary, with annual performance reviews and discretionary merit bonuses",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": 48,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-06-01T00:00:00.000Z",
        "job_posted_at_datetime_utc": "2023-04-27T03:33:21.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "Insight Global",
        "employer_logo": "https://images.squarespace-cdn.com/content/5f7f984c3ca20d1d55b276f7/1619793549819-L54X3W9Z5RD277UPNH9S/IGLogoPublic.png?content-type=image%2Fpng",
        "employer_website": "http://www.insightglobal.com",
        "job_id": "RXuPCJR_nWcAAAAAAAAAAA==",
        "job_title": "Web Developer",
        "job_apply_link": "https://jobs.insightglobal.com/find_a_job/british-columbia/vancouver/web-developer/job-277852/",
        "job_description": "Insight Global is looking for an Intermediate QA to join one of Canada's largest credit unions. The candidate will be tasked with implementing web UI's with near pixel-perfect accuracy while keeping in mind accessibility and usability. The candidate will also be responsible to customize features and experiences, and conduct detailed analysis and write technical documentation to provide recommendations on potential solutions while aligning to the current architecture.",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": null,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-07-01T00:00:00.000Z",
        "job_posted_at_datetime_utc": "2023-04-03T00:00:00.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "The Beard Struggle",
        "employer_logo": null,
        "employer_website": null,
        "job_id": "TyoctFw2s0QAAAAAAAAAAA==",
        "job_title": "Web Developer",
        "job_apply_link": "https://ca.bebee.com/job/20230427-1f91e2e7e9bf75db30293ce5183bc8cc",
        "job_description": "NIAFAZE SOLUTIONS INC. DBA The Beard Struggle located at 8385 ST GEORGE ST, UNIT 5 VANCOUVER, BC V5X 4P3 is currently looking for 1 full- time, Web Developer to join their team asap.\n\nJob Duties:\n• Develop Website architecture and determine hardware and software requirements.\n• Source, select and organize information for inclusion and design the appearance and layout and flow of the Website.\n• Create and optimize content for the Web site using a variety of graphics, database, animation and other software.\n• Research and evaluate a variety of interactive media software products.\n• Lead and co-ordinate multidisciplinary teams to develop website graphics and content.\n• Conduct Test and improve design of Web Site.\n• Maintain the appearance of Web sites by applying content standards\n• Design visual imagery of Web sites and ensuring that is consistent with organization image\n• Plan, design, write, modify, integrate and test Web-site related code.\n\nJob Requirement:\n• A bachelor's degree, or a completion of college program in computer science, graphic or web design, communications or business is required\n• 1-2 years of experience in the related field is required.\n\nTerms of Employment:\n\nWage $31.00, Overtime will be paid after 40 hours per week.\nFull time, Permanent\nJob Location: 8385 ST GEORGE ST, UNIT 5VANCOUVER, BCV5X 4P3\n\nLanguage: English\n\nWork Conditions and Physical Capabilities: Work under pressure, Attention to detail, Repetitive Task\nPersonal Suitability: Organized, Initiative, Dependability\n\nInterested Candidates can apply through –\nEmail: [email protected]\n\nMail: 8385 ST GEORGE ST, UNIT 5VANCOUVER, BCV5X 4P3",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": 12,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-05-05T00:00:00.000Z",
        "job_posted_at_datetime_utc": "2023-04-27T23:05:50.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "EY",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/EY_logo_2019.svg/220px-EY_logo_2019.svg.png",
        "employer_website": "http://www.ey.com",
        "job_id": "p_uJw48LgfQAAAAAAAAAAA==",
        "job_title": "Front End Developer (Power Apps)",
        "job_apply_link": "https://ca.linkedin.com/jobs/view/front-end-developer-power-apps-at-ey-3564821616",
        "job_description": "At EY, you’ll have the chance to build a career as unique as you are, with the global scale, support, inclusive culture and technology to become the best version of you. And we’re counting on your unique voice and perspective to help EY become even better, too. Join us and build an exceptional experience for yourself, and a better working world for all.\n\nFront End Engineer\n\nEY Client Technology is looking to fill a number of roles for a brand-new Technology hub being setup in Vancouver. This new Technology centre will work closely with the Canada business counterparts and the Global Client Technology teams to drive profitable revenue growth and enable market differentiation through asset-powered solutions.\n\nTechnology has always been at the heart of what we do and deliver at EY. Technology solutions are integrated in the client services we deliver and is key to us being more innovative as an organization. We need technology to keep an organization the size of ours working efficiently. We partner with business teams to marry their client knowledge and innovative ideas with our platforms, capabilities and technology expertise and to scale and industrialize these to provide technology solutions for the benefit of EY’s clients.\n\nThe Opportunity\n\nAs a UI Engineer @EYT, you will be in the thick of things! You will work on the most difficult & fun phases of product engineering, including:\n• Developing interactive, user-friendly web/mobile applications using the latest frameworks – both open source and proprietary;\n• Great documentation in code, code reviews to improve coding standards / performance.\n• You will also have a lot of fun innovating on Products & Technology, including:\n• Work alongside a team of Product Engineers in delivering products;\n• Have fun experimenting with emerging technology, participating in hackathons etc;\n• Help transform EY Technology into a Product organization.\n\nAnalytical/Decision Making Responsibilities:\n• 3+ years' experience in HTML, CSS, problem solving, building responsive user interfaces;\n• Handle ambiguity and able to move forward with imperfect information and get things done in a rapidly changing environment\n• Must be comfortable working in an environment where ideas are challenged;\n• Takes pride in producing clean, re-usable code and takes full ownership of the quality of code;\n• Should possess good product instinct and excellent project management skills to push projects over the finish line with sound planning and persistent execution;\n• Should know how to align resources to achieve desired results\n\nKnowledge and Skills Requirements:\n• Expert in front end / UI technologies including frameworks such as React/Angular.\n• Proficiency in Mobile/Responsive UIs.\n• Good knowledge of web services (micro frontends etc) and service-oriented principles.\n• Great understanding of RESTful architecture.\n• Experience in Data Visualization/Analysis Tools (Power BI).\n• Experience in web application development with large/internet scale consumption (distributed, scalable and high-volume systems)\n• Familiar with DevOps, Agile/Scrum.\n• Experience with software and product development lifecycle (incl. coding, coding standards and reviews, source control, testing, debugging, build, deployment and operations)\n• Good to have experience in building application using Microsoft Power Platform (Canvas Apps, Power Pages, etc)\n\nOther Requirements:\n• Must be a Canadian citizen or permanent resident. Reasonable extension of the working day should be expected commensurate with the needs to fulfil the obligations of the role.\n\nJob Requirements:\n\nEducation:\n• Required: B.E./B.Tech in Computer Science or equivalent work experience\n\nExperience:\n• Preferably 4+ /(With a minimum of 2) years of product engineering experience in renowned product organizations.\n• Have deployed code to production that takes very significant traffic volumes. Have dealt with automation / engineering issues\n• Experience working with a global team, ie.\n• Can coordinate / collaborate with teams & stakeholders in multiple geographies\n• Manage teams with participants in multiple geographies.\n• Can quickly form strong working relationships with colleagues within and outside your location.\n\nWhat Working At EY Offers\n\nWe offer a competitive remuneration package where you’ll be rewarded for your individual and team performance. Our comprehensive Total Rewards package includes support for flexible working and career development, and with FlexEY you can select benefits that suit your needs, covering holidays, health and well-being, insurance, savings and a wide range of discounts, offers and promotions. Plus, we offer:\n• Support, coaching and feedback from some of the most engaging colleagues around\n• Opportunities to develop new skills and progress your career\n• The freedom and flexibility to handle your role in a way that’s right for you\n\nIf you can confidently demonstrate that you meet the criteria above, please contact us as soon as possible.\n\nJoin us in building a better working world.\n\nApply now.\n\nEY | Building a better working world\n\nEY exists to build a better working world, helping to create long-term value for clients, people and society and build trust in the capital markets.\n\nEnabled by data and technology, diverse EY teams in over 150 countries provide trust through assurance and help clients grow, transform and operate.\n\nWorking across assurance, consulting, law, strategy, tax and transactions, EY teams ask better questions to find new answers for the complex issues facing our world today.",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": 36,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-06-10T08:14:50.000Z",
        "job_posted_at_datetime_utc": "2023-05-02T13:10:41.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "VANPLE NETWORKS",
        "employer_logo": null,
        "employer_website": null,
        "job_id": "P-SGDbFMHSYAAAAAAAAAAA==",
        "job_title": "Web Developer",
        "job_apply_link": "https://ca.indeed.com/viewjob?jk=b397ad754376924a",
        "job_description": "Job Description:\n\nBusiness and Operating name: Vanple Networks INC.\n\nPosition: Web Developer\n\nEmployer: Vanple Networks INC.\n\nWork location: #310-900 Howe Street, Vancouver, BC, V6Z 2M4\n\nBusiness Address: Same as above\n\nTerms of employment: Permanent, Full-time shift\n\nWage: $26 per hour\n\nWorking Hours: 30 – 40 hours per week\n\nBenefit: 10 paid holidays per year\n\nJob Requirements:\n\nEducation: Completion of University in computer science or\n\nCompletion of College program in computer science, graphic arts or Web design\n\nExperience: Minimum 3 year experience as web developer is required\n\nExpert knowledge with PHP, HTML5, CSS3, SASS/SCSS, JavaScript (Not just jQuery)\n\nExpert with developing responsive layouts leveraging CSS and media queries;\n\nDesign and implement robust client-side solutions with AJAX and JSON;\n\nJob Duties:\n• Build reusable components/modules for static websites with responsive design.\n• Work with API endpoints for dynamic content updating.\n• Ensure UI/UX of developed pages with near pixel-perfect design.\n• Develop and optimize front-end UI to ensure the application is rendered consistently in cross-browser environments;\n• Deploy code and database changes to staging and live server environments\n\nHow to apply:\n\nPlease send your resume to hr@vanplenetworks.com\n\nOnly selected candidate will be contacted for the interview.",
        "job_highlights": {},
        "job_min_salary": 26,
        "job_max_salary": 26,
        "job_salary_currency": "CAD",
        "job_salary_period": "HOUR",
        "job_required_experience": 36,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-05-31T22:58:52.000Z",
        "job_posted_at_datetime_utc": "2020-02-25T06:56:34.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "VeriClock",
        "employer_logo": null,
        "employer_website": null,
        "job_id": "kMExzhcTVxAAAAAAAAAAAA==",
        "job_title": "React/Typescript Web Developer [REMOTE]",
        "job_apply_link": "https://jobs.smartrecruiters.com/VeriClock/743999809767544-react-typescript-web-developer-remote-",
        "job_description": "Company Description\n\nVeriClock is a fast growing software company based in the beautiful City of Vancouver that provides a best-in-class scheduling and time tracking solution. Established in 2010, we have gained an excellent foothold in markets throughout North America.\n\nWhile we are based in Vancouver, we are now a fully remote working environment and are interviewing for this role by video conference. We are considering eligible candidates for this role from any location across Canada.\n\nJob Description\n\nWe are looking for one or more React developers to help expand and maintain our web app using React and Typescript. Please indicate your level of experience (Entry/Familiar/Proficient) in your application.\n\nQualifications\n\nQualifications\n• Frontend development experience using React\n• Experience in the use of Typescript\n\nMust Have\n• Shipped and maintained a React web app\n• Experience interfacing with REST APIs\n• Excellent debugging skills\n• Excellent written and verbal communication\n\nAssets\n• Websockets\n• Code sharing between React Native and Web React projects\n• NodeJS\n\nAdditional Information\n\nWe provide a fun, relaxed and remote working environment along with competitive compensation and a health-spending account. If this sounds like the perfect fit for you then do not hesitate to apply. We are interviewing for this role straightaway.",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": null,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": null,
        "job_posted_at_datetime_utc": "2022-03-04T21:06:14.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "TradableBits Media Inc.",
        "employer_logo": null,
        "employer_website": null,
        "job_id": "FeSgabb4RjAAAAAAAAAAAA==",
        "job_title": "Full Stack Web Developer (Software Engineer)",
        "job_apply_link": "https://www.ziprecruiter.com/c/TradableBits-Media-Inc./Job/Full-Stack-Web-Developer-(Software-Engineer)/-in-Vancouver,BC?jid=8f242f9b55d00570",
        "job_description": "Salary:\n\nFull Stack Web Developer (Software Engineer)\n\nTradable Bits, the leading fan-based marketing software platform for music and sports, is looking to fill a Full Stack Web Developer in-office position to join our development team. The successful applicant must be available to work from either our Vancouver or Victoria locations.\n\nWhat Fun Things You’ll Be Doing:\n• Writing high quality code covering everything from database to front-end\n• Working with a small, talented, and friendly development team\n• Participating in on-site deployments at festivals and arenas, as needed\n\nMust Have Skills and Experience:\n• Solid understanding of the network protocols necessary for web development (HTTP, TLS, TCP).\n• Understanding of core Unix concepts (threading, processes, memory)\n• Development experience with scripting languages (Ideally Python, Perl, PHP, Ruby)\n• Able to write clean and functional HTML / CSS / Javascript without relying on frameworks\n• Experience with at least one JS Framework or library\n• Demonstrated experience working with relational databases\n• SQL Language experience\n• BSc in Science, Math, Engineering, or related\n• Minimum of one year industry experience\n\nAdditional Expectations:\n• Initiative to manage your own workload in a constantly evolving, dynamic environment\n• Experience collaborating with a team using VCS (Git, Mercurial)\n• Excellent verbal and written communication\n• Ability to work independently and take ownership of features\n• Sense of humour and curiosity\n• Desire to work in a startup environment\n• This is primarily an in-office role to start\n\nWhat You’ll Really Like About Working Here:\n• Competitive salary and full extended benefits\n• Opportunity to work side-by-side with industry experts\n• Focus on personal development, collaboration and mentorship\n• Team-oriented environment with snacks, coffee, drinks and happy hours\n• Creative freedom, flexible work environment, and ownership over your projects\n\nPLUS your development work will be used by many of the world’s largest entertainment brands in the world, meaning you will take pride and ownership of the success of our partners like Live Nation, MLSE, OCESA, Portland Trailblazers, Lollapalooza, Austin City Limits, and Outside Lands - just to name a few.",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": 12,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-05-31T00:00:00.000Z",
        "job_posted_at_datetime_utc": "2023-04-15T07:36:25.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "STUDY2020 CONSULTING INC",
        "employer_logo": null,
        "employer_website": null,
        "job_id": "qM2tZsNfAOsAAAAAAAAAAA==",
        "job_title": "Web developer",
        "job_apply_link": "https://ca.bebee.com/job/20230429-e8ccf0927ae375b88130efc3c0acdfb9",
        "job_description": "Education: Bachelor's degree Experience: 2 years to less than 3 years Work Term: Permanent Work Language: English Hours: 30 to 40 hours per week",
        "job_highlights": {},
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_required_experience": null,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-05-07T00:00:00.000Z",
        "job_posted_at_datetime_utc": "2023-04-29T15:05:32.000Z",
        "job_employment_type": "fulltime"
    },
    {
        "employer_name": "SenseNet Inc.",
        "employer_logo": "https://avatars.githubusercontent.com/u/4069121?s=200&v=4",
        "employer_website": "http://english.sensenet.hu/engine.aspx",
        "job_id": "vjAuSBv6TMAAAAAAAAAAAA==",
        "job_title": "Web developer",
        "job_apply_link": "https://ca.indeed.com/viewjob?jk=e862d57964453319",
        "job_description": "• Education: Bachelor's degree\n• Experience: 5 years or more\nTasks\n• Consult with clients to develop and document Website requirements\n• Prepare mock-ups and storyboards\n• Develop Website architecture and determine hardware and software requirements\n• Source, select and organize information for inclusion and design the appearance, layout and flow of the Website\n• Create and optimize content for Website using a variety of graphics, database, animation and other software\n• Research and evaluate a variety of interactive media software products\n• Lead and co-ordinate multidisciplinary teams to develop Website graphics, content, capacity and interactivity\n• Conduct tests and perform security and quality controls\n• Plan, design, write, modify, integrate and test Web-site related code\nComputer and technology knowledge\n• OpenGL\n• Linux\n• Java\n• JavaScript\n• API\n• Git\n• Python\nPersonal suitability\n• Efficient interpersonal skills\n• Organized\n• Team player\n• Work Term: Permanent\n• Work Language: English\n• Hours: 40 hours per week",
        "job_highlights": {},
        "job_min_salary": 29,
        "job_max_salary": 29,
        "job_salary_currency": "CAD",
        "job_salary_period": "HOUR",
        "job_required_experience": null,
        "job_location": "Vancouver, BC, CA",
        "job_offer_expiration_datetime_utc": "2023-05-31T22:44:03.000Z",
        "job_posted_at_datetime_utc": "2023-02-10T00:02:11.000Z",
        "job_employment_type": "fulltime"
    }
]